<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>MIQ_button_apply</name>
   <tag></tag>
   <elementGuidId>1c8c0dc5-e604-41d3-b398-6e8798739040</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.x-overlay-footer__apply-btn.btn.btn--primary.btn--small</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='c3-footerId']/div[2]/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-overlay-footer__apply-btn btn btn--primary  btn--small</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Apply</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-track</name>
      <type>Main</type>
      <value>{&quot;eventFamily&quot;:&quot;LST&quot;,&quot;eventAction&quot;:&quot;ACTN&quot;,&quot;actionKind&quot;:&quot;SUBMIT&quot;,&quot;actionKinds&quot;:[&quot;SUBMIT&quot;],&quot;operationId&quot;:&quot;2489524&quot;,&quot;flushImmediately&quot;:false,&quot;eventProperty&quot;:{&quot;moduledtl&quot;:&quot;mi%3A4118%7Ciid%3A1%7Cli%3A8171%7Cluid%3A2189%7C%7C&quot;,&quot;parentrq&quot;:&quot;f87a34ed1770a1b7e7e141f8fff583a2&quot;,&quot;pageci&quot;:&quot;393a9dd0-7c2c-11eb-a4f6-32b63c404f91&quot;},&quot;aspectsBefore&quot;:{&quot;_fsrp&quot;:&quot;0&quot;,&quot;_sacat&quot;:&quot;9355&quot;,&quot;rt&quot;:&quot;nc&quot;,&quot;Screen%20Size&quot;:[&quot;5%2E0%20%2D%205%2E4%20in&quot;],&quot;_udhi&quot;:&quot;2000000&quot;,&quot;_udlo&quot;:&quot;1000000&quot;,&quot;no_encode_refine_params&quot;:&quot;1&quot;}}</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Apply</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;c3-footerId&quot;)/div[@class=&quot;x-overlay-footer__apply&quot;]/button[@class=&quot;x-overlay-footer__apply-btn btn btn--primary  btn--small&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='c3-footerId']/div[2]/button</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IDR1000000 - IDR2000000'])[1]/following::button[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Apply']/parent::*</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/button</value>
   </webElementXpaths>
</WebElementEntity>
